services:
- type: web
  name: text2pdf-flask
  runtime: python
  buildCommand:  pip install -r requirements.txt
  startCommand:  gunicorn app:app
  plan: free
  envVars:
    - key: PYTHON_VERSION
      value: 3.12
